chore: add .aab artifact, change logo and package name (#354)
* chore: bigger logo and set params for export presets

* add library to the artifacts

* test build .aab

* add persistent cache for self-hosted runners

* try fix

* try fix 2

* fix dependencies

* test

* test

* test

* test bigrunner

* test ubuntu-runner

* test bigrunner

* Update .github/workflows/android-build.yml

Signed-off-by: Lean Mendoza <leandro@decentraland.org>

* Update .github/workflows/android-build.yml

Signed-off-by: Lean Mendoza <leandro@decentraland.org>

---------

Signed-off-by: Lean Mendoza <leandro@decentraland.org>

diff --git a/.github/workflows/android-build.yml b/.github/workflows/android-build.yml
--- a/.github/workflows/android-build.yml
+++ b/.github/workflows/android-build.yml
@@ -13,9 +13,11 @@ name: Android Build
 
 jobs:
   build:
-    runs-on: self-hosted-ubuntu
+    runs-on: bigrunner
     container:
       image: docker://kuruk/dcl-godot-android-builder:latest
+      volumes:
+        - /home/user/.cache/devgodot:/github/home/.cache/devgodot
 
     steps:
       - uses: actions/checkout@v4
@@ -33,9 +35,18 @@ jobs:
       - name: Build
         run: |
           bash build-android-apk.sh
+      
+      # if libdecentraland_godot_lib.so does not exist, the build failed, nothing to upload
+      - name: Copy artifacts
+        if: success() || failure()
+        run: |
+          mkdir -p android-artifacts
+          mv godot/lib/android/arm64/libdecentraland_godot_lib.so android-artifacts/
+          mv android.apk android-artifacts/ || true
+          mv android-unsigned.aab android-artifacts/ || true
+          
       - uses: actions/upload-artifact@v3
         if: success() || failure()
         with:
           name: Android APK
-          path: |
-            android.apk
+          path: android-artifacts/
