feat: basic VR implementation (#442)
* feat: vr with lobby

* remove openxr by default

* ignores to format

* check

* check

* checkpoint

* openxr custom build

* remove player

* wip

* w

* wip

* lint and format

* add ci

* add ui texture protocol

* fix ci

* clippy

* try fix tests

* meta quest ci workflow

* remove no-needed changes

* lint ci yml

* apply review

* remove

diff --git a/.github/workflows/android-build.yml b/.github/workflows/android-build.yml
--- a/.github/workflows/android-build.yml
+++ b/.github/workflows/android-build.yml
@@ -1,8 +1,8 @@
 on:
   push:
     branches:
-      - main
-      
+    - main
+
   workflow_dispatch:
     inputs:
       branch:
@@ -10,7 +10,7 @@ on:
         required: true
         default: 'main'
 
-name: Android Build
+name: Quest & Android Builds
 
 jobs:
   build:
@@ -18,41 +18,54 @@ jobs:
     container:
       image: docker://kuruk/dcl-godot-android-builder:latest
       volumes:
-        - /home/user/.cache/devgodot:/github/home/.cache/devgodot
-
+      - /home/user/.cache/devgodot:/github/home/.cache/devgodot
     steps:
-      - uses: actions/checkout@v4
-        with:
-          ref: ${{ github.event_name == 'push' && github.ref || github.event.inputs.branch }}
-      - name: Install Android targets
-        run: |
-          echo $PATH
-      - name: Set up Rust
-        uses: actions-rs/toolchain@v1
-        with:
-          toolchain: 1.77.2
-          override: true
-          components: clippy, rustfmt
+    - uses: actions/checkout@v4
+      with:
+        ref: ${{ github.event_name == 'push' && github.ref || github.event.inputs.branch }}
+    - name: Install Android targets
+      run: |
+        echo $PATH
+    - name: Set up Rust
+      uses: actions-rs/toolchain@v1
+      with:
+        toolchain: 1.77.2
+        override: true
+        components: clippy, rustfmt
 
-      - name: Install Android targets
-        run: |
-          rustup target add aarch64-linux-android
-          rustup target add x86_64-linux-android
-      - name: Build
-        run: |
-          bash build-android-apk.sh
-      
-      # if libdclgodot.so does not exist, the build failed, nothing to upload
-      - name: Copy artifacts
-        if: success() || failure()
-        run: |
-          mkdir -p android-artifacts
-          mv godot/lib/android/arm64/libdclgodot.so android-artifacts/
-          mv android.apk android-artifacts/ || true
-          mv android-unsigned.aab android-artifacts/ || true
-          
-      - uses: actions/upload-artifact@v3
-        if: success() || failure()
-        with:
-          name: Android APK
-          path: android-artifacts/
+    - name: Install Android targets
+      run: |
+        rustup target add aarch64-linux-android
+        rustup target add x86_64-linux-android
+    - name: Build
+      run: |
+        bash build-android-apk.sh
+
+    # if libdclgodot.so does not exist, the build failed, nothing to upload
+    - name: Copy Android Artifacts
+      if: success() || failure()
+      run: |
+        mkdir -p android-artifacts
+        mv godot/lib/android/arm64/libdclgodot.so android-artifacts/
+        mv android.apk android-artifacts/ || true
+        mv android-unsigned.aab android-artifacts/ || true
+
+    - name: Copy Meta Quest Artifacts
+      if: success() || failure()
+      run: |
+        mkdir -p meta-quest-artifacts
+        mv godot/lib/android/arm64/libdclgodot.so meta-quest-artifacts/
+        mv meta-quest.apk meta-quest-artifacts/ || true
+        mv meta-quest-unsigned.aab meta-quest-artifacts/ || true
+
+    - uses: actions/upload-artifact@v4
+      if: success() || failure()
+      with:
+        name: Android APK
+        path: android-artifacts/
+
+    - uses: actions/upload-artifact@v4
+      if: success() || failure()
+      with:
+        name: Meta Quest APK
+        path: meta-quest-artifacts/
